### ISSUE TITLE
请求添加其他设备支持

### ISSUE THREAD

**Issue by lovemei2u4ever** [Kazagumo/OPi-Zero2-OPPatcher#2]
大佬您好，请问是否可以添加Orange Pi Zero 3的支持

## Orange Pi Zero 3 技术规格

| 组件           | 详细信息                                                                                            |
| -------------- | --------------------------------------------------------------------------------------------------- |
| CPU            | 全志H618高性能四核Cortex-A53处理器 1.5GHz                                                            |
| GPU            | - Mali G31 MP2<br>- 支持OpenGL ES 1.0/2.0/3.2，OpenCL 2.0，Vulkan 1.1                              |
| 内存           | - 1GB/1.5GB/2GB/4GB LPDDR4                                                                         |
| 板载存储       | 16MB SPI Flash                                                                                      |
| 电源管理       | AXP313A                                                                                             |
| 板载WiFi+蓝牙 | 支持WiFi5和蓝牙5.0                                                                                  |
| 网络           | 10M/100M/1000M以太网接口（YT8531C）                                                                           |
| 音频输入、输出 | 13Pin扩展端口支持2路输出1路输入                                                                      |
| 视频输出       | - Micro HDMI支持4K@60fps<br>- TV-Out:13Pin支持1路TV CVBS 输出                                       |
| UART           | 3Pin Debug UART                                                                                     |
| USB            | - USB 2.0 x 3（其中两个从扩展板引出）                                                                |
| SD卡接口       | Micro SD卡接口                                                                                      |
| 扩展接口       | - 26Pin GPIO接口<br>- 13Pin GPIO接口                                                                 |
| 电源输入       | 5V3A，Type-c接口                                                                                    |

**Comment by Kazagumo** [comment]
目前我的手头没有这个设备 你尝试更新uboot 设备树 patch里已经有axp313a的支持 再去armbian找几个patch就行了
h618和h616很相似 其实应该没有很难
